Tyler Baker
Assignment #5

1.) Create a 1D array of numbers from 0 to 9 called arr.. Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [2]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

2.) From arr, extract all odd numbers

In [4]:
odds = arr[arr%2==1]
print(odds)

[1 3 5 7 9]


3.) Replace all even numbers in arr with -1.


In [6]:
new_array = np.where(arr%2==0,-1,arr)
print(new_array)

[-1  1 -1  3 -1  5 -1  7 -1  9]


4.) Convert the following 1D array to a 2D array with 2 rows.
Input: np.arange(10)
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:
array([[0, 1, 2, 3, 4],
[5, 6, 7, 8, 9]])


In [7]:
new_mat = arr.reshape(2,5)
print(new_mat)

[[0 1 2 3 4]
 [5 6 7 8 9]]


5.) Create a single dimension array, array_1d, of size n containing integers 0 to n-1.
Reshape the array. The reshaped array, array_reshaped, should be n/3 columns
and 3 rows.


In [6]:
def n_minus_one_matrix(n):
    if n%3 ==2:
        arr = np.array([i for i in range(n)])
        arr = np.append(arr, ([0]))
        col_size = int((n+1)/3)
        mat = arr.reshape(3, col_size)
        print(mat)
    elif n%3 == 1:
        arr = np.array([i for i in range(n)])
        arr = np.append(arr, ([0,0]))
        col_size = int((n+2)/3)
        mat = arr.reshape(3, col_size)
        print(mat)
    else:
        arr = np.array([i for i in range(n)])
        mat = arr.reshape(3, (n/3))
        print(mat)
                          
                          

n_minus_one_matrix(10)

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 0]]


6.) Create a numpy identity matrix of size n.


In [17]:
def identity_mat(n):
    number_of_zeros = n*n
    zero_list = [0]* number_of_zeros
    zero_array = np.array([zero_list])
    mat = zero_array.reshape(n,n)
    np.fill_diagonal(mat, 1)
    print(mat)
    
identity_mat(4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


7.) Create an array filled with zeroes of size n x n (n rows, n columns).

In [19]:
def zero_mat(n):
        number_of_zeros = n*n
        zero_list = [0]* number_of_zeros
        zero_array = np.array([zero_list])
        mat = zero_array.reshape(n,n)
        print(mat)
zero_mat(2)

[[0 0]
 [0 0]]
